### ISSUE TITLE
Wrong references to vendor.qti.hardware.factory@1.0.so in clover-vendor.mk, or missing files ?

### ISSUE THREAD

**Issue by pix106** [xiaomi-sdm660/android_vendor_xiaomi_clover#1]
since https://github.com/xiaomi-sdm660/android_vendor_xiaomi_clover/commit/b7d3b6c4f144b1a7ba5d113619e7c1dcb50e1846, there may be wrong references to 
vendor.qti.hardware.factory@1.0.so in clover-vendor.mk, or those files are missing from vendor tree.

https://github.com/xiaomi-sdm660/android_vendor_xiaomi_clover/blob/b7d3b6c4f144b1a7ba5d113619e7c1dcb50e1846/clover-vendor.mk#L139 and https://github.com/xiaomi-sdm660/android_vendor_xiaomi_clover/blob/b7d3b6c4f144b1a7ba5d113619e7c1dcb50e1846/clover-vendor.mk#L211

**Comment by rcstar6696** [comment]
fixed sorry my mistake. files just misssing

**Comment by pix106** [comment]
Thanks !
